# Generated by Django 3.0.6 on 2020-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=15)),
                ('deuDate', models.CharField(max_length=15)),
                ('orderNumber', models.CharField(max_length=15)),
                ('invoiceDate', models.CharField(max_length=15)),
                ('total', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
