# Generated by Django 3.0.6 on 2020-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInvoice', '0002_invoicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
