# Generated by Django 3.0.6 on 2020-06-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInvoice', '0003_auto_20200605_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='deuDate',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoiceDate',
            field=models.CharField(max_length=25),
        ),
    ]
